version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1 # Desabilitar a telemetria, se necessário
      - DATABASE_URL="postgresql://fithabilita:habsecret@wmtechai.com:5433/fithabilita?schema=public"
